### ISSUE TITLE
Stopped working inside terraform project

### ISSUE THREAD

**Issue by Tonkonozhenko** [warrensbox/terraform-switcher#224]
```
❯ tfswitch
Reading required version from terraform file
Cannot get list from mirror: https://releases.hashicorp.com/terraform
Reading required version from constraint: ~> 1.1, >= 1.1.2
Version does not exist or invalid terraform version format.
 Format should be #.#.# or #.#.#-@# where # are numbers and @ are word characters.
 For example, 0.11.7 and 0.11.9-beta1 are valid versions
error parsing constraint: ~> 1.1, >= 1.1.2
No version found to match constraint. Follow the README.md instructions for setup. https://github.com/warrensbox/terraform-switcher/blob/master/README.md
```

**Comment by andrewsavino1** [comment]
Because the timing seems suspect, I'll note I just got a similar error:

``` Running 'tfswitch' to select the correct terraform version...
Reading required version from terraform file, constraint: = 0.14.8
No version found to match constraint. Follow the README.md instructions for setup. https://github.com/warrensbox/terraform-switcher/blob/master/README.md ```

**Comment by micahflattbuilt** [comment]
Hitting the same trouble as well.

**Comment by Tonkonozhenko** [comment]
@andrewsavino1 tried at least 5 times, both on ci and locally and it didn't work, so created the ticket. Now it works on both platforms

**Comment by micahflattbuilt** [comment]
Working for me as well. I can only assume it was some sort of download issue from the versions location.

**Comment by fcastagninizoom** [comment]
It stopped working once again...

`Reading required version from constraint: ~> 1.0.0
No version found to match constraint. Follow the README.md instructions for setup. https://github.com/warrensbox/terraform-switcher/blob/master/README.md`

**Comment by acoppolawb** [comment]
Experiencing the same issue

**Comment by aderuelle** [comment]
ditto here

**Comment by vigohe** [comment]
<img width="943" alt="image" src="https://user-images.githubusercontent.com/761298/167492394-34162bec-b906-41d4-a506-7e122188c059.png">

https://status.hashicorp.com/

```
In progress - Scheduled maintenance is currently in progress. We will provide updates as necessary.
May 9, 19:01 UTC
Update - We will be undergoing scheduled maintenance during this time.
Update - We will be undergoing scheduled maintenance during this time.
Scheduled - The Releases Site, releases.hashicorp.com, will undergo scheduled maintenance on Monday, May 9th beginning at 12pm PST. We expect this maintenance to complete within 3 hours.

During this time, intermittent service blips may occur until the maintenance completes. We'll post updates as necessary throughout the maintenance period.
```

**Comment by aderuelle** [comment]
[		semver = `\/(\d+\.\d+\.\d+)\/`](https://github.com/warrensbox/terraform-switcher/blob/092ccf5400887b7e02e296a8ff507fb2f6f7c4eb/lib/list_versions.go#L33)

```html
<a href="/terraform/0.5.0">terraform_0.5.0</a>
```

Seems like the links in the release page are now missing the trailing slash in href=

**Comment by aderuelle** [comment]
workaround

In first terminal

```console
mkdir release
curl  'https://releases.hashicorp.com/terraform' | sed  's#">t#/">t#' > release/index.html
python3 -m http.server
```
Then in another terminal

```console
$ tfswitch -m http://127.0.0.1:8000/release
```

**Comment by allen-servedio** [comment]
@aderuelle are you planning on pushing a PR to try to fix this? Not sure if @warrensbox is aware this change broke the tool... But maybe a quick fix can get this operational again?

**Comment by micahflattbuilt** [comment]
I have a working hack for this. testing it locally then I'll figure out how to make a PR.

**Comment by micahflattbuilt** [comment]
PR is up: https://github.com/warrensbox/terraform-switcher/pull/225

**Comment by jensenbox** [comment]
Hashicorp reports the maintenance is now complete. The problem still persists. I suspect the PR might fix this.

**Comment by yermulnik** [comment]
FYI: https://www.hashicorp.com/blog/announcing-the-hashicorp-releases-api

**Comment by mantoniocc** [comment]
Hi everyone,
I think that I have a similar problem.
I'm trying to switch some specific terraform versions, however I got the following error:
`The provided terraform version does not exist. Try `tfswitch -l` to see all available versions.`

I tried with two different versions of tfswitch. Initially:
`➜  ~ tfswitch -v

Version: 0.12.1092`

And then I have upgraded to:

`➜  ~ tfswitch -v

Version: 0.13.1218`

![image](https://user-images.githubusercontent.com/13409704/167526859-90eaf003-cffc-44b8-9b9a-5c343d29ca98.png)

**Comment by moizdhanji** [comment]
ditto ... getting the same error ... it was working fine a few hours back

**Comment by ArneRiemann4711** [comment]
Same problem here (;

**Comment by Akhisar** [comment]
Using the temp version at the moment.

https://github.com/Jukie/terraform-switcher/releases/tag/0.13.12345

**Comment by parberge** [comment]
> Hi everyone, I think that I have a similar problem. I'm trying to switch some specific terraform versions, however I got the following error: `The provided terraform version does not exist. Try `tfswitch -l` to see all available versions.`
> 
> I tried with two different versions of tfswitch. Initially: `➜ ~ tfswitch -v
> 
> Version: 0.12.1092`
> 
> And then I have upgraded to:
> 
> `➜ ~ tfswitch -v
> 
> Version: 0.13.1218`
> 
> ![image](https://user-images.githubusercontent.com/13409704/167526859-90eaf003-cffc-44b8-9b9a-5c343d29ca98.png)

I'm also a bit curious in why it needs to get list of releases even when a specific version is provided;

```
❯ tfswitch 1.1.9
Cannot get list from mirror: https://releases.hashicorp.com/terraform
The provided terraform version does not exist. Try `tfswitch -l` to see all available versions.
```
But I suspect it needs to find the direct download link for the release anyway.

**Comment by Vladyslav-Miletskyi** [comment]
> workaround
> 
> In first terminal
> 
> ```
> mkdir release
> curl  'https://releases.hashicorp.com/terraform' | sed  's#">t#/">t#' > release/index.html
> python3 -m http.server
> ```
> 
> Then in another terminal
> 
> ```
> $ tfswitch -m http://127.0.0.1:8000/release
> ```

Works only, when the version is present on the machine!

```
::ffff:127.0.0.1 - - [10/May/2022 11:08:01] code 404, message File not found
::ffff:127.0.0.1 - - [10/May/2022 11:08:01] "GET /release/1.1.9/terraform_1.1.9_darwin_amd64.zip HTTP/1.1" 404 -
[Error] : Unable to download from http://127.0.0.1:8000/release/1.1.9/terraform_1.1.9_darwin_amd64.zip
```

As I actually need to download it (inside CI)... decided to go with good old curl

**Comment by harry-patel-jisc** [comment]
we've gone with a direct version download as a workaround for now (which we'd like to revert as soon as this is fixed)

```
      cd /usr/bin
      curl -s -qL -o terraform.zip https://releases.hashicorp.com/terraform/1.1.7/terraform_1.1.7_linux_amd64.zip
      unzip terraform.zip
```

**Comment by sysunix** [comment]
Hi,
we have the same error, a lot of our jobs that are not working , have you planned a fix or a workaround ?
Thanks

**Comment by Marcel-MTL** [comment]
> Hi, we have the same error, a lot of our jobs that are not working , have you planned a fix or a workaround ? Thanks

Look like pull request is in place : [pull request LINK](https://github.com/warrensbox/terraform-switcher/pull/225)

**Comment by vbakayev** [comment]
> FYI: https://www.hashicorp.com/blog/announcing-the-hashicorp-releases-api

I would love this to become a new source of truth, but it provides quite limited subset of versions at the moment:

curl -sS https://api.releases.hashicorp.com/v1/releases/terraform/ | jq -r '.[].version' | sort
1.1.4
1.1.5
1.1.6
1.1.7
1.1.8
1.1.9
1.2.0-alpha-20220328
1.2.0-alpha20220413
1.2.0-beta1
1.2.0-rc1

**Comment by skyzyx** [comment]
I do have a question about the error message.

> Reading required version from terraform file
> Cannot get list from mirror: https://releases.hashicorp.com/terraform
> Reading required version from constraint: ~> 1
> Version does not exist or invalid terraform version format.
>  Format should be #.#.# or #.#.#-@# where # are numbers and @ are word characters.
>  For example, 0.11.7 and 0.11.9-beta1 are valid versions
> error parsing constraint: ~> 1
> No version found to match constraint. Follow the README.md instructions for setup. https://github.com/warrensbox/terraform-switcher/blob/master/README.md

I use `~> 1` which is equivalent to `>= 1.0.0, < 2.0.0`, but shorter. It works in Terraform, and has been working in `tfswitch` for quite some time. I feel these instructions in the error message might be incorrect/outdated.

**Comment by yermulnik** [comment]
@skyzyx 
> I use `~> 1` which is equivalent to `>= 1.0.0, < 2.0.0`, but shorter.

This is unrelated to the issue per se, though JFYI: this is equivalent to `>= 1.0.0` **without** `< 2.0.0` (ref: https://www.terraform.io/language/expressions/version-constraints#-3)

**Comment by skyzyx** [comment]
> @skyzyx
> 
> > I use `~> 1` which is equivalent to `>= 1.0.0, < 2.0.0`, but shorter.
> 
> This is unrelated to the issue per se, though JFYI: this is equivalent to `>= 1.0.0` **without** `< 2.0.0` (ref: https://www.terraform.io/language/expressions/version-constraints#-3)

Then this might be a bug in `tfswitch` (worthy of a separate ticket). `~> 1.0` would cause `tfswitch` to give me `1.0.x` rather than `1.1.x`.

**Comment by yermulnik** [comment]
> Then this might be a bug in `tfswitch` (worthy of a separate ticket). `~> 1.0` would cause `tfswitch` to give me `1.0.x` rather than `1.1.x`.

Which version of `tfswitch` do you use?
https://github.com/warrensbox/terraform-switcher/releases/tag/0.13.1218

**Comment by mengesb** [comment]
@skyzyx that's a different, but yes prevalent issue. It's not following semver whe doing `tfswitch -u 1.0` which should pull `1.1.9` currently.

This is present in 0.13.1218

**Comment by luckeyca** [comment]
This problem still exists as of now. see the test below. curl https://releases.hashicorp.com/terraform works, but tfswitch -l does NOT. So wonder if the output format changed which screwed up the code logic given tfswitch was still working yesterday for me, but not today. I use this daily

```
tfswitch -v

Version: 0.13.1218

tfswitch 1.1.9 

Cannot get list from mirror: https://releases.hashicorp.com/terraform
The provided terraform version does not exist. Try `tfswitch -l` to see all available versions.

tfswitch -l   

Cannot get list from mirror: https://releases.hashicorp.com/terraform
[ERROR] : List is empty

```

**Comment by DP19** [comment]
> 

it shows them all, the default is only 10. Should be relatively easy to implement an interface to use this instead of the current url. Working on a patch at the moment

https://releases.hashicorp.com/docs/api/v1/#operation/getReleasesV1

**Comment by aderuelle** [comment]
@DP19 did you manage to get the `after` parameter right ? I can't get past the 1.0.10 release here ...

**Comment by DP19** [comment]
> @DP19 did you manage to get the `after` parameter right ? I can't get past the 1.0.10 release here ...

@aderuelle 
Yeah... Their docs aren't quite right. There is a query param for `before` that you should use instead of `after` using the `timestamp_created` as the param entry

**Comment by Jukie** [comment]
@aderuelle same here - It seems impossible to get anything older than 20 releases (max limit allowed).

We really need a `before` option or `after` should actually return the most recent release _after_ the given timestamp. Anyone know where that code is hosted?

**Comment by Jukie** [comment]
For example specifying the timestamp from 0.1.0 will still always return the latest release from last week.
```
$ curl -s  https://api.releases.hashicorp.com/v1/releases/terraform\?after\=2017-07-12T06:41:24.000Z\&limit\=1 | jq '.[] | .timestamp_created'
"2022-05-04T17:00:45.000Z"
```

**Comment by lutzwillek-tomtom** [comment]
🤔  I wonder if, in the interest of solving the problem quickly, it might not be better to use https://github.com/warrensbox/terraform-switcher/pull/225 to fix this issue - and to open a separate issue for using the new API. 

I think a lot of people are using tfswitch in their pipelines, and eventually they don't want to use a local mirror (nice workaround by the way, thanks for it  @aderuelle) and thus desperately waiting for a working tfswitch version to be released. 

Just a thought - ymmv. 💭

**Comment by Jukie** [comment]
Oh yeah I agree, #225 should (imo) be merged in the meantime but I'd still like to figure out the new stuff.

**Comment by shibir** [comment]
Team anyone working on fix ?

**Comment by RUBenGAMArrarodRiguEZ-ToMtOm** [comment]
> Team anyone working on fix ?
see https://github.com/warrensbox/terraform-switcher/pull/225

**Comment by bdlake** [comment]
> Using the temp version at the moment.
> 
> https://github.com/Jukie/terraform-switcher/releases/tag/0.13.12345

This version does not work for me
```
~/bin$ tfswitch -l
Cannot get list from mirror: https://releases.hashicorp.com/terraform
[ERROR] : List is empty
```
Even tried `tfswitch 0.14.7` thinking the list was still broken, but specifying a specific version doesn't work either.

**Comment by warrensbox** [comment]
Fixed with release 0.13.1221

**Comment by lutzwillek-tomtom** [comment]
@warrensbox https://github.com/warrensbox/terraform-switcher/blob/0.13.1221/CHANGELOG.md is not updated?
As it still mentions `[0.13.1201] - 2021-11-28`

**Comment by aderuelle** [comment]
> For example specifying the timestamp from 0.1.0 will still always return the latest release from last week.
> 
> ```
> $ curl -s  https://api.releases.hashicorp.com/v1/releases/terraform\?after\=2017-07-12T06:41:24.000Z\&limit\=1 | jq '.[] | .timestamp_created'
> "2022-05-04T17:00:45.000Z"
> ```

> FYI: https://www.hashicorp.com/blog/announcing-the-hashicorp-releases-api

@DP19 @Jukie, is there a github issue about using this API within tfswitch yet ?

**Comment by Jukie** [comment]
@aderuelle I couldn't find a github repo for it so I opened one [here](https://github.com/hashicorp/terraform/issues/31033) in the terraform repo and also sent them an email.

**Comment by romanbakaleyko** [comment]
> Fixed with release 0.13.1221
Still doesn't work

==> Upgrading warrensbox/tap/tfswitch
  0.13.1218 -> 0.13.1221
  
$ tfswitch --version
Version: 0.13.1221

$ tfswitch -l
2022/05/12 11:09:57 [Error] : Getting url: Get "https://releases.hashicorp.com/terraform/": dial tcp: i/o timeout

$ tfswitch -U
2022/05/12 11:15:15 [Error] : Getting url: Get "https://releases.hashicorp.com/terraform/": dial tcp: i/o timeout

**Comment by yermulnik** [comment]
> 2022/05/12 11:09:57 [Error] : Getting url: Get "https://releases.hashicorp.com/terraform/": dial tcp: i/o timeout

@romanbakaleyko Does the https://releases.hashicorp.com/terraform/ show up a list of TF releases for you when opened with your preferred web browser?

**Comment by romanbakaleyko** [comment]
it does work when I open it in browser, it does work when I run it in a docker container (ubuntu 20.04) but it doesn't when I run it in my macos laptop. I removed ~/.terraform.versions/ with a hope that it caches something but that didn't help. Seems to me it either issue with macos version or my local problem.

**Comment by romanbakaleyko** [comment]
hmm, so from multiple attempts one time it worked fine, so this local problem on my macos, thanks for a response.

**Comment by Jukie** [comment]
Piggy-backing off this because it had a lot of activity.
Anyone interested in assisting the tfswitch project as a collaborator/maintainer? I'll let @warrensbox add additional info but he's looking for folks to help review PR's. I've already offered my help moving forward but the more the merrier.
